version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    volumes:
      - ./gateway-ha-persistence-postgres.sql:/docker-entrypoint-initdb.d/gateway-ha-persistence-postgres.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  trino1:
    image: trinodb/trino
    container_name: trino1
    ports:
      - "8081:8080"
    environment:
      JAVA_TOOL_OPTIONS: "-Dhttp-server.process-forwarded=true"

  trino2:
    image: trinodb/trino
    container_name: trino2
    ports:
      - "8082:8080"
    environment:
      JAVA_TOOL_OPTIONS: "-Dhttp-server.process-forwarded=true"

  gateway:
    image: openjdk:11-jre-slim
    container_name: trino-gateway
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./gateway-ha.jar:/app/gateway-ha.jar
      - ./quickstart-config.yaml:/app/quickstart-config.yaml
    working_dir: /app
    entrypoint: ["java", "-Xmx1g", "-jar", "./gateway-ha.jar", "./quickstart-config.yaml"]
    ports:
      - "8080:8080"

networks:
  default:
    driver: bridge
